//
//  SYLocalizableConstant.h
//  Bookworm
//
//  Created by Killua Liu on 12/16/15.
//  Copyright (c) 2015 Syzygy. All rights reserved.
//

#ifndef Bookworm_SYLocalizableConstant_h
#define Bookworm_SYLocalizableConstant_h

#define TAB_TITLE_HOME                  NSLocalizedString(@"Home", "")
#define TAB_TITLE_WISH                  NSLocalizedString(@"Wish", "")
#define TAB_TITLE_MESSAGE               NSLocalizedString(@"Message", "")
#define TAB_TITLE_ME                    NSLocalizedString(@"Me", "")

#define BUTTON_TITLE_YES                NSLocalizedString(@"Yes", "")
#define BUTTON_TITLE_NO                 NSLocalizedString(@"No", "")
#define BUTTON_TITLE_CANCEL             NSLocalizedString(@"Cancel", "")
#define BUTTON_TITLE_DONE               NSLocalizedString(@"Done", "")
#define BUTTON_TITLE_OKAY               NSLocalizedString(@"Okay", "")
#define BUTTON_TITLE_EXIT               NSLocalizedString(@"Exit", "")
#define BUTTON_TITLE_SAVE               NSLocalizedString(@"Save", "")
#define BUTTON_TITLE_SEND               NSLocalizedString(@"Send", "")
#define BUTTON_TITLE_SIGNIN             NSLocalizedString(@"SignIn", "")
#define BUTTON_TITLE_SIGNUP             NSLocalizedString(@"SignUp", "")
#define BUTTON_TITLE_SIGNOUT            NSLocalizedString(@"SignOut", "")
#define BUTTON_TITLE_NEXT               NSLocalizedString(@"Next", "")
#define BUTTON_TITLE_SKIP               NSLocalizedString(@"Skip", "")
#define BUTTON_TITLE_SEND               NSLocalizedString(@"Send", "")
#define BUTTON_TITLE_RESEND             NSLocalizedString(@"Resend", "")
#define BUTTON_TITLE_LOOK_AROUND        NSLocalizedString(@"LookAround", "")
#define BUTTON_TITLE_FORGOT_PASSWORD    NSLocalizedString(@"ForgotPassword", "")
#define BUTTON_TITLE_DELETE             NSLocalizedString(@"Delete", "")
#define BUTTON_TITLE_REFRESH            NSLocalizedString(@"Refresh", "")
#define BUTTON_TITLE_MARK_READ          NSLocalizedString(@"MarkRead", "")
#define BUTTON_TITLE_MARK_UNREAD        NSLocalizedString(@"MarkUnread", "")
#define BUTTON_TITLE_FOLLOW             NSLocalizedString(@"Follow", "")
#define BUTTON_TITLE_UNFOLLOW           NSLocalizedString(@"Unfollow", "")
#define BUTTON_TITLE_EXCHANGE           NSLocalizedString(@"Exchange", "")
#define BUTTON_TITLE_CHAT               NSLocalizedString(@"Chat", "")
#define BUTTON_TITLE_REPLY              NSLocalizedString(@"Reply", "")
#define BUTTON_TITLE_ACCEPT             NSLocalizedString(@"Accept", "")
#define BUTTON_TITLE_REJECT             NSLocalizedString(@"Reject", "")
#define BUTTON_TITLE_RATING             NSLocalizedString(@"Rating", "")
#define BUTTON_TITLE_REPORT             NSLocalizedString(@"Report", "")
#define BUTTON_TITLE_SHARE              NSLocalizedString(@"Share", "")
#define BUTTON_TITLE_WECHAT             NSLocalizedString(@"Wechat", "")
#define BUTTON_TITLE_WECHAT_MOMENTS     NSLocalizedString(@"WechatMoments", "")
#define BUTTON_TITLE_QQ                 NSLocalizedString(@"QQ", "")
#define BUTTON_TITLE_WEIBO              NSLocalizedString(@"Weibo", "")
#define BUTTON_TITLE_QZONE              NSLocalizedString(@"Qzone", "")
#define BUTTON_TITLE_DOUBAN             NSLocalizedString(@"Douban", "")
#define BUTTON_TITLE_TAKE_PHOTO         NSLocalizedString(@"TakePhoto", "")
#define BUTTON_TITLE_CHOOSE_PHOTO       NSLocalizedString(@"ChoosePhoto", "")
#define BUTTON_TITLE_SET_CHAT_BG        NSLocalizedString(@"SetChatBackground", "")
#define BUTTON_TITLE_RESTORE_DEFAULT_BG NSLocalizedString(@"RestoreDefaultBackground", "")

#define TITLE_EDIT_PROFILE              NSLocalizedString(@"EditProfile", "")
#define TITLE_CHANGE_NICKNAME           NSLocalizedString(@"ChangeNickname", "")
#define TITLE_CHANGE_PASSWORD           NSLocalizedString(@"ChangePassword", "")

#define TITLE_NICKNAME                  NSLocalizedString(@"Nickname", "")
#define TITLE_GENDER                    NSLocalizedString(@"Gender", "")
#define TITLE_LOCATION                  NSLocalizedString(@"Location", "")

#define TEXT_GENDER_MALE                NSLocalizedString(@"Male", "")
#define TEXT_GENDER_FEMALE              NSLocalizedString(@"Female", "")
#define TEXT_USER_AGREEMENT             NSLocalizedString(@"UserAgreement", "")
#define TEXT_AGREE_USER_AGREEMENT       NSLocalizedString(@"AgreeUserAgreement", "")
#define TEXT_SINGLE_TAP_REFRESH         NSLocalizedString(@"SingleTapRefresh", "")

#define PH_REPORT_OTHER_REASON          NSLocalizedString(@"ReportOtherReason", "")
#define PH_FEEDBACK                     NSLocalizedString(@"Feedback", "")

#define HUD_CLEARING_CACHE              NSLocalizedString(@"ClearingCache", "")
#define HUD_CACHE_CLEAR_DONE            NSLocalizedString(@"CacheClearDone", "")
#define HUD_NETWORK_UNSTABLE            NSLocalizedString(@"NetworkUnstable", "")
#define HUD_CANNOT_CONNECT_TO_HOST      NSLocalizedString(@"CannotConnectToHost", "")
#define HUD_NOT_CONNECTED_TO_INTERNET   NSLocalizedString(@"NotConnectedToInternet", "")
#define HUD_CONNECTING_IM_SERVER        NSLocalizedString(@"ConnectingIMServer", "")
#define HUD_MOBILE_INVALID              NSLocalizedString(@"MobileInvalid", "")
#define HUD_MOBILE_TAKEN                NSLocalizedString(@"MobileTaken", "")
#define HUD_MOBILE_NOT_FOUND            NSLocalizedString(@"MobileNotFound", "")
#define HUD_EMAIL_INVALID               NSLocalizedString(@"EmailInvalid", "")
#define HUD_EMAIL_TAKEN                 NSLocalizedString(@"EmailTaken", "")
#define HUD_EMAIL_TOO_LONG              NSLocalizedString(@"EmailTooLong", "")
#define HUD_EMAIL_NOT_FOUND             NSLocalizedString(@"EmailNotFound", "")
#define HUD_PASSWORD_WRONG              NSLocalizedString(@"PasswordWrong", "")
#define HUD_PASSWORD_TOO_SHORT          NSLocalizedString(@"PasswordTooShort", "")
#define HUD_PASSWORD_INVALID            NSLocalizedString(@"PasswordInvalid", "")
#define HUD_SMS_CODE_WRONG              NSLocalizedString(@"SMSCodeWrong", "")
#define HUD_NICKNAME_TOO_LONG           NSLocalizedString(@"NicknameTooLong", "")
#define HUD_SIGNING_IN                  NSLocalizedString(@"SigningIn", "")
#define HUD_CREATING_ACCOUNT            NSLocalizedString(@"CreatingAccount", "")
#define HUD_THANKS_FEEDBACK             NSLocalizedString(@"ThanksFeedback", "")

#define TITLE_PHOTOS                    NSLocalizedString(@"Photos", "")
#define TITLE_CAMERA                    NSLocalizedString(@"Camera", "")
#define TITLE_MICROPHONE                NSLocalizedString(@"Microphone", "")
#define TITLE_SETTINGS                  NSLocalizedString(@"Settings", "")
#define TITLE_KICK_OUT                  NSLocalizedString(@"KickOut", "")
#define TITLE_VERSION_INVALID           NSLocalizedString(@"VersionInvalid", "")

#define MSG_ACCESS_PHOTOS_SETTING       NSLocalizedString(@"AccessPhotosSetting", "")
#define MSG_ACCESS_CAMERA_SETTING       NSLocalizedString(@"AccessCameraSetting", "")
#define MSG_ACCESS_MICROPHONE_SETTING   NSLocalizedString(@"AccessMicrophoneSetting", "")
#define MSG_SIGNIN_AGAIN                NSLocalizedString(@"SignInAgain", "")
#define MSG_APP_VERSION_UNAVAILABLE     NSLocalizedString(@"AppVersionUnavailable", "")

#endif
