//
//  SYTextConstant.h
//  Bookworm
//
//  Created by Killua Liu on 12/16/15.
//  Copyright (c) 2015 Syzygy. All rights reserved.
//

#ifndef Bookworm_SYTextConstant_h
#define Bookworm_SYTextConstant_h

#define TAB_TITLE_HOME                  SYLocalizedString(@"Home")
#define TAB_TITLE_WISH                  SYLocalizedString(@"Wish")
#define TAB_TITLE_MESSAGE               SYLocalizedString(@"Message")
#define TAB_TITLE_ME                    SYLocalizedString(@"Me")

#define BUTTON_TITLE_YES                SYLocalizedString(@"Yes")
#define BUTTON_TITLE_NO                 SYLocalizedString(@"No")
#define BUTTON_TITLE_CANCEL             SYLocalizedString(@"Cancel")
#define BUTTON_TITLE_DONE               SYLocalizedString(@"Done")
#define BUTTON_TITLE_OKAY               SYLocalizedString(@"Okay")
#define BUTTON_TITLE_EXIT               SYLocalizedString(@"Exit")
#define BUTTON_TITLE_SAVE               SYLocalizedString(@"Save")
#define BUTTON_TITLE_SEND               SYLocalizedString(@"Send")
#define BUTTON_TITLE_SIGNIN             SYLocalizedString(@"SignIn")
#define BUTTON_TITLE_SIGNUP             SYLocalizedString(@"SignUp")
#define BUTTON_TITLE_SIGNOUT            SYLocalizedString(@"SignOut")
#define BUTTON_TITLE_NEXT               SYLocalizedString(@"Next")
#define BUTTON_TITLE_SKIP               SYLocalizedString(@"Skip")
#define BUTTON_TITLE_SEND               SYLocalizedString(@"Send")
#define BUTTON_TITLE_RESEND             SYLocalizedString(@"Resend")
#define BUTTON_TITLE_LOOK_AROUND        SYLocalizedString(@"LookAround")
#define BUTTON_TITLE_FORGOT_PASSWORD    SYLocalizedString(@"ForgotPassword")
#define BUTTON_TITLE_DELETE             SYLocalizedString(@"Delete")
#define BUTTON_TITLE_REFRESH            SYLocalizedString(@"Refresh")
#define BUTTON_TITLE_MARK_READ          SYLocalizedString(@"MarkRead")
#define BUTTON_TITLE_MARK_UNREAD        SYLocalizedString(@"MarkUnread")
#define BUTTON_TITLE_FOLLOW             SYLocalizedString(@"Follow")
#define BUTTON_TITLE_UNFOLLOW           SYLocalizedString(@"Unfollow")
#define BUTTON_TITLE_EXCHANGE           SYLocalizedString(@"Exchange")
#define BUTTON_TITLE_CHAT               SYLocalizedString(@"Chat")
#define BUTTON_TITLE_REPLY              SYLocalizedString(@"Reply")
#define BUTTON_TITLE_ACCEPT             SYLocalizedString(@"Accept")
#define BUTTON_TITLE_REJECT             SYLocalizedString(@"Reject")
#define BUTTON_TITLE_RATING             SYLocalizedString(@"Rating")
#define BUTTON_TITLE_REPORT             SYLocalizedString(@"Report")
#define BUTTON_TITLE_SHARE              SYLocalizedString(@"Share")
#define BUTTON_TITLE_WECHAT             SYLocalizedString(@"Wechat")
#define BUTTON_TITLE_WECHAT_MOMENTS     SYLocalizedString(@"WechatMoments")
#define BUTTON_TITLE_QQ                 SYLocalizedString(@"QQ")
#define BUTTON_TITLE_WEIBO              SYLocalizedString(@"Weibo")
#define BUTTON_TITLE_QZONE              SYLocalizedString(@"Qzone")
#define BUTTON_TITLE_DOUBAN             SYLocalizedString(@"Douban")
#define BUTTON_TITLE_TAKE_PHOTO         SYLocalizedString(@"TakePhoto")
#define BUTTON_TITLE_CHOOSE_PHOTO       SYLocalizedString(@"ChoosePhoto")
#define BUTTON_TITLE_SET_CHAT_BG        SYLocalizedString(@"SetChatBackground")
#define BUTTON_TITLE_RESTORE_DEFAULT_BG SYLocalizedString(@"RestoreDefaultBackground")

#define TITLE_EDIT_PROFILE              SYLocalizedString(@"EditProfile")
#define TITLE_CHANGE_NICKNAME           SYLocalizedString(@"ChangeNickname")
#define TITLE_CHANGE_PASSWORD           SYLocalizedString(@"ChangePassword")

#define TITLE_NICKNAME                  SYLocalizedString(@"Nickname")
#define TITLE_GENDER                    SYLocalizedString(@"Gender")
#define TITLE_LOCATION                  SYLocalizedString(@"Location")

#define TEXT_GENDER_MALE                SYLocalizedString(@"Male")
#define TEXT_GENDER_FEMALE              SYLocalizedString(@"Female")
#define TEXT_USER_AGREEMENT             SYLocalizedString(@"UserAgreement")
#define TEXT_AGREE_USER_AGREEMENT       SYLocalizedString(@"AgreeUserAgreement")
#define TEXT_SINGLE_TAP_REFRESH         SYLocalizedString(@"SingleTapRefresh")

#define PH_REPORT_OTHER_REASON          SYLocalizedString(@"ReportOtherReason")
#define PH_FEEDBACK                     SYLocalizedString(@"Feedback")

#define HUD_CLEARING_CACHE              SYLocalizedString(@"ClearingCache")
#define HUD_CACHE_CLEAR_DONE            SYLocalizedString(@"CacheClearDone")
#define HUD_NETWORK_UNSTABLE            SYLocalizedString(@"NetworkUnstable")
#define HUD_CANNOT_CONNECT_TO_HOST      SYLocalizedString(@"CannotConnectToHost")
#define HUD_NOT_CONNECTED_TO_INTERNET   SYLocalizedString(@"NotConnectedToInternet")
#define HUD_CONNECTING_IM_SERVER        SYLocalizedString(@"ConnectingIMServer")
#define HUD_MOBILE_INVALID              SYLocalizedString(@"MobileInvalid")
#define HUD_MOBILE_TAKEN                SYLocalizedString(@"MobileTaken")
#define HUD_MOBILE_NOT_FOUND            SYLocalizedString(@"MobileNotFound")
#define HUD_EMAIL_INVALID               SYLocalizedString(@"EmailInvalid")
#define HUD_EMAIL_TAKEN                 SYLocalizedString(@"EmailTaken")
#define HUD_EMAIL_TOO_LONG              SYLocalizedString(@"EmailTooLong")
#define HUD_EMAIL_NOT_FOUND             SYLocalizedString(@"EmailNotFound")
#define HUD_PASSWORD_WRONG              SYLocalizedString(@"PasswordWrong")
#define HUD_PASSWORD_TOO_SHORT          SYLocalizedString(@"PasswordTooShort")
#define HUD_PASSWORD_INVALID            SYLocalizedString(@"PasswordInvalid")
#define HUD_SMS_CODE_WRONG              SYLocalizedString(@"SMSCodeWrong")
#define HUD_NICKNAME_TOO_LONG           SYLocalizedString(@"NicknameTooLong")
#define HUD_SIGNING_IN                  SYLocalizedString(@"SigningIn")
#define HUD_CREATING_ACCOUNT            SYLocalizedString(@"CreatingAccount")
#define HUD_THANKS_FEEDBACK             SYLocalizedString(@"ThanksFeedback")

#define TITLE_PHOTOS                    SYLocalizedString(@"Photos")
#define TITLE_CAMERA                    SYLocalizedString(@"Camera")
#define TITLE_MICROPHONE                SYLocalizedString(@"Microphone")
#define TITLE_SETTINGS                  SYLocalizedString(@"Settings")
#define TITLE_KICK_OUT                  SYLocalizedString(@"KickOut")
#define TITLE_VERSION_INVALID           SYLocalizedString(@"VersionInvalid")

#define MSG_ACCESS_PHOTOS_SETTING       SYLocalizedString(@"AccessPhotosSetting")
#define MSG_ACCESS_CAMERA_SETTING       SYLocalizedString(@"AccessCameraSetting")
#define MSG_ACCESS_MICROPHONE_SETTING   SYLocalizedString(@"AccessMicrophoneSetting")
#define MSG_SIGNIN_AGAIN                SYLocalizedString(@"SignInAgain")
#define MSG_APP_VERSION_UNAVAILABLE     SYLocalizedString(@"AppVersionUnavailable")

#endif
